studyService:
  replicaCount: 1
  image:
    repository: khg1115/groovy-study-service
    tag: "msa-v1"
  port: 8082
  database:
    host: mysql
    port: 3306
    name: study_db
    username: study_service
    parameters: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
  dbPool:
    maxSize: "10"
    minIdle: "2"
  jwt:
    jwksUrl: "http://identity-service:8081/.well-known/jwks.json"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
    cacheTtlSeconds: "300"
  identityService:
    url: "http://identity-service:8081"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
  kafka:
    bootstrapServers: "kafka:9092"
    securityProtocol: "SASL_PLAINTEXT"
    saslMechanism: "PLAIN"

config:
  corsAllowedOrigins: "http://localhost:5173"
  timezone: "Asia/Seoul"
