studyService:
  replicaCount: 1
  image:
    repository: ttt103/groovy-study-service
    tag: "113cb8e0af4ea62b727e04c34fc027b6271a6495"
  port: 8082
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  javaOpts: "-XX:MaxRAMPercentage=50.0 -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m -Xss256k"
  hpa:
    enabled: false # TEMP: JVM 메모리 옵션 전/후 비교 테스트 위해 replica=1 고정 (테스트 끝나면 true로 복구)
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  database:
    host: mysql
    port: 3306
    name: study_db
    username: study_service
    parameters: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
  dbPool:
    maxSize: "10"
    minIdle: "2"
  jwt:
    jwksUrl: "http://identity-service:8081/.well-known/jwks.json"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
    cacheTtlSeconds: "300"
  identityService:
    url: "http://identity-service:8081"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
  kafka:
    bootstrapServers: "kafka:9092"
    securityProtocol: "SASL_PLAINTEXT"
    saslMechanism: "PLAIN"

config:
  corsAllowedOrigins: "http://localhost:5173"
  timezone: "Asia/Seoul"

sealedSecretData:
  studyService:
    dbPassword: AgA/0w/IOfVh0XbiVByvAWn2zg5YlEYFYjAn3vCUy+4gtyrwjGnSe+GV5TyemN3lIKvE9J8hGRceUWojSOJd2rcxd8pUAd0lLAmjQobyOEvSr9KrEZGkx6Q4wi84mcLrk+k79509sfqLRC1SwQGczcb1jI1ztgDWXFXzcxUH6nmBA2D2R6e/J2EevforjsAr7anf5442DrcIUaoUlVVXPzAXHw9JaKJraL+nrLQSFQ5/n8N0CoxtOQ+CbQBNb3khdVyXNtTZMbVEbYfuqClnbDV0iZo+f2P48iI6RgP+jR7u8/ayCD6N87f/LX9g1b78V5ixPYIoJWdf19hRbL2lRjEW2RzTS/zPTx2wbxnV60LwSL9j2TaL1rLKy6rihunkIw5AByPd0gKjPR9nXxXe3pImxGQMcVJeXbpgkPwavaSF93LNu2YXRxMv3+hffpICRgkAIuJegM37q/UOdtBF4JPwUSG+YreA1Tl78cznmJkyxLCakQtw2TL9mrKR3MORaTdvq09qqWoKOXfMCTiImqb539bw9Id33rfEBYgAh7yR2IsC5tC/KdAhx5c25eGDuVEbbIoeNOXTXC3FLx6xhGsg/ge6XAmuYwpql/7Z72I4EjR+IDHjIubNJ6Ks7oeuNqrDxcKObud98PI/YtmSXf1OodCsYAOmgQgzHEYs5uf+oWo/DEX0sf9XU9reLHUu3XkFJTlS4kSBZOc5
