{
 "title": "Kafka Exporter Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Brokers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer Group Members",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Notification Topic Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  kafka_topic_partition_current_offset{\n    topic=\"notification-events\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification In-Sync Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kafka_topic_partition_in_sync_replica{\n    topic=\"notification-events\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification Topic Offset",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kafka_topic_partition_current_offset{\n    topic=\"notification-events\"\n  }\n)",
     "legendFormat": "{{consumergroup}} / {{topic}}"
    }
   ]
  },
  {
   "title": "Notification Topic Offset Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(\n  kafka_topic_partition_current_offset{\n    topic=\"notification-events\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}