{
 "title": "Groovy MySQL Monitoring",
 "description": "A quickstart to setup the Prometheus MySQL Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "label_values(mysql_up, job)" },
   {
    "name": "instance",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "up/down" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "**Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Gateway p95",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(http_server_requests_seconds_bucket{job=\"api-gateway\"}[5m])\n  )\n) * 1000",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{job=~\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "App DB Connection Pool(HikariCP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active)",
     "legendFormat": "Total Active"
    },
    { "expr": "sum(hikaricp_connections_idle)", "legendFormat": "Total Idle" },
    {
     "expr": "sum(hikaricp_connections_pending)",
     "legendFormat": "Total Pending"
    },
    { "expr": "sum(hikaricp_connections_max)", "legendFormat": "Total Max" }
   ]
  },
  {
   "title": "서비스별 Active",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (application) (\n  hikaricp_connections_active\n)",
     "legendFormat": "{{application}}"
    },
    {
     "expr": "sum(hikaricp_connections_active)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pool Usage by Service",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum by (application) (\n  hikaricp_connections_active\n)\n/\nsum by (application) (\n  hikaricp_connections_max\n)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mysql_global_status_threads_connected{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Current Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_status_max_used_connections{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_global_variables_max_connections{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "timeseries",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mysql_global_status_threads_connected{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mysql_global_status_threads_running{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "sum(avg_over_time(mysql_global_status_threads_running{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "MySQL Questions",
   "type": "timeseries",
   "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{job=~\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Temporary Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "MySQL Temporary Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_created_tmp_tables{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Created Tmp Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_created_tmp_disk_tables{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Created Tmp Disk Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_created_tmp_files{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Created Tmp Files"
    }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "timeseries",
   "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_full_join{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Full Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_full_range_join{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Full Range Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_range{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_range_check{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Range Check"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_select_scan{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Select Scan"
    }
   ]
  },
  { "title": "Performance Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "MySQL Slow Queries",
   "type": "timeseries",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_slow_queries{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  { "title": "Connections & Lock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "MySQL Aborted Connections",
   "type": "timeseries",
   "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_aborted_connects{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Aborted Connects (attempts)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_aborted_clients{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Aborted Clients (timeout)"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "timeseries",
   "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_table_locks_immediate{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Table Locks Immediate"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_table_locks_waited{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Table Locks Waited"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "timeseries",
   "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool,  TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_page_size{job=~\"$job\", instance=~\"$instance\"} * on (instance) mysql_global_status_buffer_pool_pages{job=~\"$job\", instance=~\"$instance\", state=\"data\"})",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "sum(mysql_global_variables_innodb_log_buffer_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "sum(mysql_global_variables_innodb_additional_mem_pool_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "sum(mysql_global_status_innodb_mem_dictionary{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "sum(mysql_global_variables_key_buffer_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "sum(mysql_global_variables_query_cache_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "sum(mysql_global_status_innodb_mem_adaptive_hash{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Adaptive Hash Index Size"
    },
    {
     "expr": "sum(mysql_global_variables_tokudb_cache_size{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "TokuDB Cache Size"
    }
   ]
  },
  { "title": "Command, Handlers, Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Top Command Counters",
   "type": "timeseries",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{job=~\"$job\", instance=~\"$instance\"}[$__interval])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  }
 ]
}