apiVersion: v1
kind: Secret
metadata:
  name: study-service-secret
  labels:
    app: study-service
type: Opaque
stringData:
  SPRING_DEV_DB_PASSWORD: {{ required "secret.studyService.dbPassword is required" .Values.secret.studyService.dbPassword | quote }}
