apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: study-rds-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: study-rds-secret
      type: Opaque
      data:
        - objectName: username
          key: SPRING_DEV_DB_USERNAME
        - objectName: password
          key: SPRING_DEV_DB_PASSWORD
  parameters:
    region: ap-northeast-2
    usePodIdentity: "true"
    objects: |
      - objectName: "groovy/rds/study"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"