{{- $service := .Values.studyService -}}
{{- if $service.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: study-service
  labels:
    app: study-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: study-service
  minReplicas: {{ $service.hpa.minReplicas }}
  maxReplicas: {{ $service.hpa.maxReplicas }}
  metrics:
    {{- if $service.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $service.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $service.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $service.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
