apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-service
  labels:
    app: study-service
spec:
  {{- if not .Values.studyService.hpa.enabled }}
  replicas: {{ .Values.studyService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: study-service
  template:
    metadata:
      labels:
        app: study-service
    spec:
      serviceAccountName: study-service-sa
      volumes:
        - name: rds-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: study-rds-secrets
      containers:
        - name: study-service
          image: "{{ .Values.studyService.image.repository }}:{{ .Values.studyService.image.tag }}"
          imagePullPolicy: {{ .Values.studyService.image.pullPolicy }}
          volumeMounts:
            - name: rds-secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          envFrom:
            - configMapRef:
                name: study-service-config
            - secretRef:
                name: study-rds-secret
          env:
            - name: KAFKA_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: app-jaas-config
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.studyService.javaOpts | quote }}
          ports:
            - containerPort: {{ .Values.studyService.port }}
              protocol: TCP
          {{- if .Values.studyService.resources }}
          resources:
            {{- toYaml .Values.studyService.resources | nindent 12 }}
          {{- end }}
