identityService:
  replicaCount: 1
  image:
    repository: ttt103/groovy-identity-service
    tag: "11ad5bd2e73652f656c62b48ccfe2c7ca6322fb8"
  port: 8081
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  database:
    host: mysql
    port: 3306
    name: identity_db
    username: identity_service
    parameters: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
  dbPool:
    maxSize: "10"
    minIdle: "2"

config:
  corsAllowedOrigins: "http://localhost:5173"
  timezone: "Asia/Seoul"
