apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: api-gateway-config
          ports:
            - containerPort: {{ .Values.apiGateway.port }}
              protocol: TCP
              # actuator port를 위한 management port 추가 - 변
            - containerPort: {{ .Values.apiGateway.managementPort }}
              name: management
          {{- if .Values.apiGateway.resources }}
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
          {{- end }}
