{{- range $name, $instance := .Values.mysql.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-mysql
  labels:
    app: {{ $name }}-mysql
    groovy.io/service: {{ $name }}
spec:
  selector:
    app: {{ $name }}-mysql
  ports:
    - name: mysql
      protocol: TCP
      port: {{ $.Values.mysql.port }}
      targetPort: {{ $.Values.mysql.port }}
{{- end }}