{{- range $name, $instance := .Values.mysql.instances }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}-mysql-secret
  labels:
    app: {{ $name }}-mysql
    groovy.io/service: {{ $name }}
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: {{ required (printf "sealedSecretData.mysql.%s.rootPassword is required" $name) (index $.Values.sealedSecretData.mysql $name "rootPassword") | quote }}
    MYSQL_PROVISIONER_PASSWORD: {{ required (printf "sealedSecretData.mysql.%s.provisionerPassword is required" $name) (index $.Values.sealedSecretData.mysql $name "provisionerPassword") | quote }}
    00-provisioner-init.sql: {{ required (printf "sealedSecretData.mysql.%s.provisionerInitSql is required" $name) (index $.Values.sealedSecretData.mysql $name "provisionerInitSql") | quote }}
  template:
    metadata:
      name: {{ $name }}-mysql-secret
      labels:
        app: {{ $name }}-mysql
        groovy.io/service: {{ $name }}
    type: Opaque
{{- end }}