{{- range $name, $instance := .Values.mysql.instances }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-mysql-data
  labels:
    app: {{ $name }}-mysql
    groovy.io/service: {{ $name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $instance.persistence.size }}
{{- end }}