apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: groovy-redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: groovy-redis-data
              mountPath: /data
      volumes:
        - name: groovy-redis-data
          persistentVolumeClaim:
            claimName: groovy-redis-data
