secret:
  jwtSecretKey: "CHANGE_ME"
  mysqlRootPassword: "CHANGE_ME"
  springDevDbPassword: "CHANGE_ME"
  identityService:
    dbPassword: "CHANGE_ME"
  studyService:
    dbPassword: "CHANGE_ME"
    kafkaSaslJaasConfig: ""
  contentService:
    dbPassword: "CHANGE_ME"
    kafkaSaslJaasConfig: ""
  calendarService:
    dbPassword: "CHANGE_ME"
    kafkaSaslJaasConfig: ""
  notificationService:
    dbPassword: "CHANGE_ME"
    kafkaSaslJaasConfig: ""
  kafka:
    brokerPassword: "CHANGE_ME"
    applicationPassword: "CHANGE_ME"
  grafanaAdminPassword: "CHANGE_ME"
