secret:
  mysqlRootPassword: "CHANGE_ME"
  identityService:
    dbPassword: "CHANGE_ME"
  studyService:
    dbPassword: "CHANGE_ME"
  contentService:
    dbPassword: "CHANGE_ME"
  calendarService:
    dbPassword: "CHANGE_ME"
  notificationService:
    dbPassword: "CHANGE_ME"
  kafka:
    brokerPassword: "CHANGE_ME"
    applicationPassword: "CHANGE_ME"
  grafanaAdminPassword: "CHANGE_ME"
