apiGateway:
  image:
    tag: "msa-v1-amd64"

identityService:
  image:
    tag: "msa-v1-amd64"

studyService:
  image:
    tag: "msa-v1-amd64"

contentService:
  image:
    tag: "msa-v1-amd64"

calendarService:
  image:
    tag: "msa-v1-amd64"

notificationService:
  image:
    tag: "msa-v1-amd64"

frontend:
  image:
    tag: "msa-v2"
