apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  labels:
    app: identity-service
spec:
  {{- if not .Values.identityService.hpa.enabled }}
  replicas: {{ .Values.identityService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      serviceAccountName: identity-service-sa
      volumes:
        - name: rds-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: identity-rds-secrets
      containers:
        - name: identity-service
          image: "{{ .Values.identityService.image.repository }}:{{ .Values.identityService.image.tag }}"
          imagePullPolicy: {{ .Values.identityService.image.pullPolicy }}
          volumeMounts:
            - name: rds-secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          envFrom:
            - configMapRef:
                name: identity-service-config
            - secretRef:
                name: identity-rds-secret
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.identityService.javaOpts | quote }}
          ports:
            - containerPort: {{ .Values.identityService.port }}
              protocol: TCP
          {{- if .Values.identityService.resources }}
          resources:
            {{- toYaml .Values.identityService.resources | nindent 12 }}
          {{- end }}
