calendarService:
  replicaCount: 1
  image:
    repository: ttt103/groovy-calendar-service
    tag: "msa-v1"
  port: 8084
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  database:
    host: mysql
    port: 3306
    name: calendar_db
    username: calendar_service
    parameters: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
  dbPool:
    maxSize: "10"
    minIdle: "2"
  jwt:
    jwksUrl: "http://identity-service:8081/.well-known/jwks.json"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
    cacheTtlSeconds: "300"
  studyService:
    url: "http://study-service:8082"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
  kafka:
    bootstrapServers: "kafka:9092"
    securityProtocol: "SASL_PLAINTEXT"
    saslMechanism: "PLAIN"

config:
  corsAllowedOrigins: "http://localhost:5173"
  timezone: "Asia/Seoul"

sealedSecretData:
  calendarService:
    dbPassword: AgAZn0Pc5I47Tarf6Lc3WL8cjb9bbDURwVaLZQ/pAhPvXBmI+CXtdcA8+6gfoOtlB7pKsSzadZQcB8xZzjQdDcU6KUQOEnC48bI6RR0LBCbmnNp/tnX6fvBmY1n6M3uj+BpWUlESvOPQHMZenWyQdMbSiLbIJmR+56RMV+svd59f7r5Eg+zgraiXGrf7rkyDRwEjsw+mAmHlhxKiHIA/CtMWETx/oUD0ESO/WorjA0DbEfIFHOGArcWRNcLJCzm6XWFiQO/3Q8rQkvCBopHh+E7u0a3gKgGaEieVYS+7GlplotTMB0/e1kJ+MikAajlewkd2zB2X03akcJampgiXdXOzjBdNWCThQKLeiD2nEZT2jah+WULtNGJgBTuvllQ0M5GaFbTWIw5T2+7gw5ido5iedLBldusY6eZtWTllBBtfclKPN9InOqUEbqVRPlFedVea0lAbHnC77DUfF+NUhUPeqDuNeOOTq1n+h+hGFDmlqN6A5UPB5umfvQ/h4apra2pcwtppiXPWgd7kvuGkpDmCBm1g0A/uugFF1T/ssncQfGaEY+uur+M4LSLaM7xgWcK//f9bWaXk7FYzZ7msVczaXr/DL4kJ5LtMYFEorq23F2lBTjEg3Fc9Zi2PuvSwKV0kfz6eaRMoiMdV50z2VBgkvlm0dxhZdq7cp0x4TyPj0KdP3VopjzNjU41NHKvidk47E86zAYKP8cKG
