apiVersion: v1
kind: Secret
metadata:
  name: calendar-service-secret
  labels:
    app: calendar-service
type: Opaque
stringData:
  SPRING_DEV_DB_PASSWORD: {{ required "secret.calendarService.dbPassword is required" .Values.secret.calendarService.dbPassword | quote }}
  KAFKA_SASL_JAAS_CONFIG: {{ .Values.secret.calendarService.kafkaSaslJaasConfig | default (printf "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"%s\" password=\"%s\";" .Values.kafka.security.applicationUsername (required "secret.kafka.applicationPassword is required" .Values.secret.kafka.applicationPassword)) | quote }}
