apiVersion: v1
kind: Secret
metadata:
  name: calendar-service-secret
  labels:
    app: calendar-service
type: Opaque
stringData:
  SPRING_DEV_DB_PASSWORD: {{ required "secret.calendarService.dbPassword is required" .Values.secret.calendarService.dbPassword | quote }}
