apiVersion: v1
kind: ConfigMap
metadata:
  name: groovy-config
data:
  # Database
  MYSQL_DATABASE: {{ .Values.config.mysqlDatabase | quote }}
  MYSQL_PORT: {{ .Values.mysql.port | quote }}
  SPRING_DEV_DB_URL: {{ printf "jdbc:mysql://mysql:%v/%s?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=%s" .Values.mysql.port .Values.config.mysqlDatabase .Values.config.timezone | quote }}
  SPRING_DEV_DB_USERNAME: {{ .Values.config.mysqlUsername | quote }}

  # Redis
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}

  # Application Port
  FRONTEND_PORT: {{ .Values.frontend.port | quote }}

  # Database Pool
  DB_POOL_MAX_SIZE: {{ .Values.config.dbPool.maxSize | quote }}
  DB_POOL_MIN_IDLE: {{ .Values.config.dbPool.minIdle | quote }}

  # Browser / CORS
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}

  # Timezone
  TZ: {{ .Values.config.timezone | quote }}
  
  # Grafana
  GF_SECURITY_ADMIN_USER: {{ .Values.config.grafanaAdminUser | quote }}
