apiVersion: v1
kind: Secret
metadata:
  name: content-service-secret
  labels:
    app: content-service
type: Opaque
stringData:
  SPRING_DEV_DB_PASSWORD: {{ required "secret.contentService.dbPassword is required" .Values.secret.contentService.dbPassword | quote }}
