apiVersion: v1
kind: Secret
metadata:
  name: content-service-secret
  labels:
    app: content-service
type: Opaque
stringData:
  SPRING_DEV_DB_PASSWORD: {{ required "secret.contentService.dbPassword is required" .Values.secret.contentService.dbPassword | quote }}
  KAFKA_SASL_JAAS_CONFIG: {{ .Values.secret.contentService.kafkaSaslJaasConfig | default (printf "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"%s\" password=\"%s\";" .Values.kafka.security.applicationUsername (required "secret.kafka.applicationPassword is required" .Values.secret.kafka.applicationPassword)) | quote }}
