apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secret
  labels:
    app: identity-service
type: Opaque
stringData:
  SPRING_DEV_DB_PASSWORD: {{ required "secret.identityService.dbPassword is required" .Values.secret.identityService.dbPassword | quote }}
