apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: groovy-mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: groovy-config
            - secretRef:
                name: groovy-secret
          ports:
            - containerPort: {{ .Values.mysql.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'mysqladmin ping -h localhost -uroot -p"$MYSQL_ROOT_PASSWORD"'
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: groovy-mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: groovy-mysql-data
          persistentVolumeClaim:
            claimName: groovy-mysql-data
