apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groovy-mysql-data
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
