apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  labels:
    app: notification-service
type: Opaque
stringData:
  SPRING_DEV_DB_PASSWORD: {{ required "secret.notificationService.dbPassword is required" .Values.secret.notificationService.dbPassword | quote }}
  KAFKA_SASL_JAAS_CONFIG: {{ .Values.secret.notificationService.kafkaSaslJaasConfig | default (printf "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"%s\" password=\"%s\";" .Values.kafka.security.applicationUsername (required "secret.kafka.applicationPassword is required" .Values.secret.kafka.applicationPassword)) | quote }}
