apiVersion: v1
kind: Secret
metadata:
  name: groovy-secret
  labels:
    app: groovy
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secret.jwtSecretKey | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword | quote }}
  SPRING_DEV_DB_PASSWORD: {{ .Values.secret.springDevDbPassword | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.secret.GF_SECURITY_ADMIN_PASSWORD.password | quote }}
