apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: {{ .Values.tempo.httpPort }}
      targetPort: {{ .Values.tempo.httpPort }}
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.tempo.otlpHttpPort }}
      targetPort: {{ .Values.tempo.otlpHttpPort }}
      protocol: TCP
