apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hpas
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/KDT-Team26/groovy-infra.git
    targetRevision: main
    path: helm/hpas
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: groovy-kubernates
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
