# Istio-컨트롤 플레인(istiod) 설치용 App
# 현재 상황 (일단 최소로 구성)
# 레플리카 셋 : 1개
# cpu: 100m
# memory: 256Mi
# limits:
#  cpu: 500m
#  memory: 512Mi

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: "1.30.4"
    helm:
      values: |
        replicaCount: 1
        autoscaleEnabled: false
        pilot:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        global:
          istioNamespace: istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  # istiod가 기동하면서 istiod-default-validator 웹훅의 caBundle을 런타임에 직접 주입한다
  # 그래서 ArgoCD가 달라졌다고 판단을 하고 계속 싱크를 맞춰버림 (무한 알림 문제 유발)
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
