# kube-state-metrics — Kubernetes API 객체들(Deployment, Pod, Service 등)의 상태 메트릭을 생성하여 Prometheus가 수집하도록 함.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics

    targetRevision: "5.26.0"
    helm:
      values: |
        # 특별히 추가 옵션이 필요하지 않다면 빈 상태로 두거나 기본값 적용
        prometheusScrape: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
