apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-service
  labels:
    app: calendar-service
spec:
  {{- if not .Values.calendarService.hpa.enabled }}
  replicas: {{ .Values.calendarService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: calendar-service
  template:
    metadata:
      labels:
        app: calendar-service
    spec:
      containers:
        - name: calendar-service
          image: "{{ .Values.calendarService.image.repository }}:{{ .Values.calendarService.image.tag }}"
          imagePullPolicy: {{ .Values.calendarService.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: calendar-service-config
            - secretRef:
                name: calendar-service-secret
          env:
            - name: KAFKA_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: app-jaas-config
          ports:
            - containerPort: {{ .Values.calendarService.port }}
              protocol: TCP
          {{- if .Values.calendarService.resources }}
          resources:
            {{- toYaml .Values.calendarService.resources | nindent 12 }}
          {{- end }}
