kafka:
  replicaCount: 1
  image:
    repository: apache/kafka
    tag: "4.3.1"
    pullPolicy: IfNotPresent
  nodeId: 1
  processRoles: "broker,controller"
  clusterId: "4L6g3nShT-eMCtK--X86sw"
  listeners:
    clientName: CLIENT
    controllerName: CONTROLLER
    clientPort: 9092
    controllerPort: 9093
    advertisedHost: kafka
  security:
    protocolMap: "CONTROLLER:PLAINTEXT,CLIENT:SASL_PLAINTEXT"
    saslEnabledMechanisms: "PLAIN"
    saslMechanismInterBrokerProtocol: "PLAIN"
    brokerUsername: "broker"
    applicationUsername: "app"
  replication:
    offsetsTopicFactor: 1
    transactionStateLogFactor: 1
    transactionStateLogMinIsr: 1
  autoCreateTopics: "true"
  persistence:
    enabled: false
    size: 1Gi
    mountPath: /var/lib/kafka/data

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  port: 6379
  persistence:
    size: 100Mi

config:
  timezone: "Asia/Seoul"
