apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  labels:
    app: alloy
spec:
  replicas: {{ .Values.alloy.replicaCount }}
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      containers:
        - name: alloy
          image: "{{ .Values.alloy.image.repository }}:{{ .Values.alloy.image.tag }}"
          imagePullPolicy: {{ .Values.alloy.image.pullPolicy }}
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:{{ .Values.alloy.port }}
          ports:
            - containerPort: {{ .Values.alloy.port }}
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: alloy-config
