apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.config.grafanaAdminUser | quote }}
  TZ: {{ .Values.config.timezone | quote }}
  GF_FEATURE_TOGGLES_ENABLE: "traceqlSearch"
