apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-exporter-secret
  labels:
    app: kafka-exporter
spec:
  encryptedData:
    KAFKA_PASSWORD: {{ required "sealedSecretData.kafkaExporterPassword is required" .Values.sealedSecretData.kafkaExporterPassword | quote }}
  template:
    metadata:
      name: kafka-exporter-secret
      labels:
        app: kafka-exporter
    type: Opaque
