apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    app: kafka-exporter
spec:
  type: ClusterIP
  selector:
    app: kafka-exporter
  ports:
    - name: metrics
      port: {{ .Values.kafkaExporter.port }}
      targetPort: metrics
      protocol: TCP
