{{- if .Values.loki.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groovy-loki-data
  labels:
    app: loki

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.loki.persistence.size }}
{{- end }}