{{- range $name, $instance := .Values.mysqldExporter.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-mysqld-exporter
  labels:
    app: {{ $name }}-mysqld-exporter
    groovy.io/service: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}-mysqld-exporter
  ports:
    - name: metrics
      port: {{ $.Values.mysqldExporter.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}