{{- range $name, $instance := .Values.mysqldExporter.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-mysqld-exporter
  labels:
    app: {{ $name }}-mysqld-exporter
    groovy.io/service: {{ $name }}
spec:
  replicas: {{ $.Values.mysqldExporter.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}-mysqld-exporter
  template:
    metadata:
      labels:
        app: {{ $name }}-mysqld-exporter
        groovy.io/service: {{ $name }}
    spec:
      containers:
        - name: mysqld-exporter
          image: "{{ $.Values.mysqldExporter.image.repository }}:{{ $.Values.mysqldExporter.image.tag }}"
          imagePullPolicy: {{ $.Values.mysqldExporter.image.pullPolicy }}
          args:
            - "--mysqld.address={{ $instance.host }}:{{ $.Values.mysql.port }}"
            - "--mysqld.username={{ $.Values.mysqldExporter.mysql.username }}"
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $name }}-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - name: metrics
              containerPort: {{ $.Values.mysqldExporter.port }}
              protocol: TCP
{{- end }}