apiVersion: v1
kind: ConfigMap
metadata:
  name: groovy-tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: {{ .Values.tempo.httpPort }}

    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: "0.0.0.0:{{ .Values.tempo.otlpHttpPort }}"

    ingester:
      max_block_duration: {{ .Values.tempo.ingester.maxBlockDuration | default "5m" }}
      trace_idle_period: {{ .Values.tempo.ingester.traceIdlePeriod | default "10s" }}
      flush_check_period: {{ .Values.tempo.ingester.flushCheckPeriod | default "10s" }}

    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks

    usage_report:
      reporting_enabled: false
