contentService:
  replicaCount: 1
  image:
    repository: ttt103/groovy-content-service
    tag: "6987e87279d41ad2e16ec5a0e6f42e9ff6052c43"
  port: 8083
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  javaOpts: "-XX:MaxRAMPercentage=50.0 -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m -Xss256k"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  database:
    host: mysql
    port: 3306
    name: content_db
    username: content_service
    parameters: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
  dbPool:
    maxSize: "10"
    minIdle: "2"
  jwt:
    jwksUrl: "http://identity-service:8081/.well-known/jwks.json"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
    cacheTtlSeconds: "300"
  identityService:
    url: "http://identity-service:8081"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
  studyService:
    url: "http://study-service:8082"
    connectTimeoutMs: "2000"
    readTimeoutMs: "3000"
  kafka:
    bootstrapServers: "kafka:9092"
    securityProtocol: "SASL_PLAINTEXT"
    saslMechanism: "PLAIN"

config:
  corsAllowedOrigins: "http://localhost:5173"
  timezone: "Asia/Seoul"

sealedSecretData:
  contentService:
    dbPassword: AgCb6e90C+fDp7TDGqhaTTwba4rWCRsHpukvqUvUKVmRhKdbIGuWEVfja4fkfEkQpjshh4SdkvnkOK1FoemBB29FUBMEIt/nWt6G8nzv7yFodTyMJG1+XAGogbhbnLG9BBlvm4HHFvuqJI51IREc6CuXK8M0GT8Eplrp8HlCHqz+ksCWOOZXiFg35EGGCg/oGNh9297qkg353cAWkPgQiturFPKPmxskScbRxMa8DnHhSheYlqPg2jYvLECiYU0pQ+h91VMoQ0wQhi97nkAW6VDntF8P30U+JLZH0Nc726/CSbKWwFBS1ck1mXU6i5pALJzFwz1J6WhI7FKd7nlMyYSO92xXKvK4aNVVFHbPtLpIfnMUuyTiQxGXkv62z9hT4NwwneFnJgs1cLWr9AIGMNLaTMTZ+G0R3KcOnlNJj8qoZYzMTr+ysSOzhfu7iZ5cTq1dnwXJSdXogGfVWhn8+IejQc3WGFqMAzMTO3KmlwWEbyCePjWqDPTruTsfVFIQue2MLMRoFhV5U8n6vFk0/8wVQW6z3re9KBjfkCyNIsjkjDkH1Ue+/T5jJU2HV98PhcbpgTgyYTIja3cr7yrLkRVmDtqF3Z+TQMcTaiGysv5KqvRr5klbgEm0Vs0kO1IZXUpbVkqcxzJg9YveQv6YDezdhVJbUWzrVI/o5gzUcBbft4fIWIUdUA3SRnVmEY5XkSv9dzTX/2wo+E6V
